FROM golang:1.21-alpine AS builder
WORKDIR /src/
COPY . .
RUN go build -o /app/webapi ./cmd/webapi
FROM debian:bookworm-slim
EXPOSE 3000 4000
WORKDIR /app/
COPY --from=builder /app/webapi ./
CMD ["/app/webapi"]
